name: Production Demo

on: 
  workflow_call:
    inputs: 
      REPO:
        required: true
        type: string
      REF_NAME:
        required: true
        type: string
  workflow_dispatch:

jobs:
  demo:
      runs-on: ubuntu-latest
      concurrency:
        group: deploy-docs-production
        cancel-in-progress: true
      steps:
        - run: echo 'Production:Trigger by ${{inputs.REPO}}:${{inputs.REF_NAME}}'