name: Testing Demo

on: 
  workflow_call:
    inputs:
      REPO:
        required: true
        type: string
      REF_NAME:
        required: true
        type: string
  workflow_dispatch:

jobs:
  demo:
      runs-on: ubuntu-latest
      concurrency:
        group: deploy-testing
        cancel-in-progress: true
      steps:
        - run: echo 'Testing:Trigger by ${{inputs.REPO}}:${{inputs.REF_NAME}} - ${{secrets.DEMO_TOKEN}}'