name: Production Demo

on:
  workflow_call:
    inputs: 
      REPO:
        required: true
        type: string
      REF_NAME:
        required: true
        type: string
    secrets:
      DEMO_TOKEN:
        description: 'Only a demo for test'
        required: true
  workflow_dispatch:

jobs:
  demo:
      runs-on: ubuntu-latest
      concurrency:
        group: deploy-production
        cancel-in-progress: true
      steps:
        - run: echo 'Production:Trigger by ${{inputs.REPO}}:${{inputs.REF_NAME}} - ${{secrets.DEMO_TOKEN}}'