name: Passively triggered github action

on:
  repository_dispatch:
    types: [trigger-another-repo]
  
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger info
        run: echo '"repo":"${{github.event.client_payload.repository}}"; "job":"${{github.event.client_payload.job}}"'
        