name: Passively triggered github action

on:
  repository_dispatch:
    types: [trigger-another-repo]

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger info
        run: echo '"repo":"${{github.event.client_payload.repository}}"; "ref_type":"${{github.event.client_payload.ref_type}}"; "ref_name":"${{github.event.client_payload.ref_name}}"; "job":"${{github.event.client_payload.job}}"'

  trigger-testing-action:
    if:  ${{github.event.client_payload.ref_type == 'branch'}} && ${{github.event.client_payload.ref_name == 'testing'}}
    uses: ./.github/workflows/demo-testing.yml

  trigger-production-action:
    if: ${{github.event.client_payload.ref_type == 'branch'}} && ${{github.event.client_payload.ref_name == 'main'}}   
    uses: ./.github/workflows/demo-production.yml
  
  test-skip:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World!